# Generated by Django 3.2.4 on 2021-10-17 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_auto_20211017_1943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameModel(
            old_name='Socials',
            new_name='Social',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': 'skills'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name_plural': 'socials'},
        ),
    ]
