# Generated by Django 3.2.4 on 2021-10-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_auto_20211017_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='Url',
        ),
        migrations.RemoveField(
            model_name='social',
            name='name',
        ),
        migrations.AddField(
            model_name='social',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='social',
            name='facebook',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='social',
            name='github',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='social',
            name='hacker_rank',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='social',
            name='linkedin',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='social',
            name='twitter',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
