# Generated by Django 3.2.4 on 2021-10-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0005_auto_20211017_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='email',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='facebook',
            new_name='social_url',
        ),
        migrations.RemoveField(
            model_name='social',
            name='github',
        ),
        migrations.RemoveField(
            model_name='social',
            name='hacker_rank',
        ),
        migrations.RemoveField(
            model_name='social',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='social',
            name='twitter',
        ),
    ]
