# Generated by Django 3.2.4 on 2021-10-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0006_auto_20211017_2301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
